allowBuilds:
  bcrypt: set this to true or false
  cpu-features: set this to true or false
  esbuild: set this to true or false
  protobufjs: set this to true or false
  sharp: true
  ssh2: set this to true or false
  unrs-resolver: true
onlyBuiltDependencies:
  - sharp
  - unrs-resolver
